CREATE DATABASE IF NOT EXISTS 'crud_db';
USE 'crud_db';
CREATE TABLE IF NOT EXISTS 'users' (
    'id' INT AUTO_INCREMENT PRIMARY KEY,
    'nombre' VARCHAR(255) NOT NULL,
    'correo' VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;